---
sudo: required
dist: trusty

language: python

python: "2.7"

env:
  - ANSIBLE_VERSION=2.1.2.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y shellcheck

install:
  - pip install ansible==$ANSIBLE_VERSION

script:
  - ./test.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net##phatypus"
    template:
      - "(%{repository_name}) %{build_number}: %{branch}@%{commit} %{author} -> %{message} %{build_url}"
    use_notice: true
