---
language: python

python: "2.7"

env:
  - ANSIBLE_VERSION=1.9.2

install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  - printf "[defaults]\nroles_path=roles" > ansible.cfg

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

notifications:
  irc:
    channels:
      - "chat.freenode.net##phatypus"
