---
- hosts: all
  sudo: yes
  gather_facts: yes
  vars_files:
    - "./vars/private/users.yml"
    - "./vars/private/znc.yml"

  roles:
    # ssh depends on users, users depends on bash
    - ssh
    - locale
    - sudo
    - yum-update
    - yum-common
    - selinux
    - ntp
    - firewall
    - znc
