---
- hosts: all
  sudo: yes
  gather_facts: yes
  vars_files:
    - "./private/vars/users.yml"
  vars:
    v_environment: development
    v_restart_delay: 90
    v_restart_timeout: 180

  roles:
    # ssh depends on users, users depends on bash
    - ssh
    - locale
    - sudo
    - yum-update
    - yum-common
    - selinux
    - ntp
    - firewall

  post_tasks:
  - name: restart server
    command: shutdown -r +1 "Restart triggered by Ansible"
    async: 0
    poll: 0

  - name: wait for server to restart
    local_action:
      module: wait_for
        host={{ ansible_ssh_host }}
        port={{ ansible_ssh_port }}
        delay={{ v_restart_delay }}
        timeout={{ v_restart_timeout }}
    sudo: no
