---
- hosts: all
  sudo: yes
  gather_facts: yes
  vars_files:
    - "./vars/yum-common.yml"

  roles:
    - firewall
    - yum-common
    - yum-update
    - selinux

- hosts: all
  sudo: yes
  gather_facts: yes
  vars_files:
    - "./vars/private/users.yml"
    - "./vars/ssh.yml"
    - "./vars/znc.yml"

  roles:
    # ssh depends on users, users depends on bash
    - ssh
    - locale
    - sudo
    - ntp
    - znc
