---
- hosts: all
  sudo: yes
  gather_facts: yes
  vars_files:
    - "./vars/private/users.yml"
    - "./vars/yum-cron.yml"

  roles:
    - locale
    - yum-update
    - yum-common
    - yum-cron
    - ntp
    - bash
    - users
    - ssh
    - sudo
    - firewall
    # selinux requires a reboot if going from disabled to enabled
    - selinux

- hosts: all
  sudo: yes
  gather_facts: yes
  vars_files:
    - "./vars/znc.yml"

  roles:
    - znc
