---
- hosts: all
  become: true
  gather_facts: true

  roles:
    - locale
    - yum-update
    - yum-common
    - yum-cron
    - ntp
    - bash
    - users
    - ssh
    - sudo
    - firewall
    # selinux requires a reboot if going from disabled to enabled
    - selinux
