---
- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - "{{ v_yum_packages }}"
  notify: restart yum-cron
  tags:
    - yum

- name: configure yum-cron
  template: src=yum-cron.conf.j2
    dest={{ v_yum_cron_config }}
    backup=yes
    owner=0 group=0 mode=0644
  notify:
    - restart ssh
  tags:
    - yum
