---
- name: install ntp
  yum: name={{ v_ntp_package }} state=present
  tags:
    - ntp
    - yum

- name: ntp configuration file update
  template: src=ntp.conf.j2
    dest={{ v_ntp_config }}
    backup=yes
    owner=0 group=0 mode=0644
  notify:
    - restart ntp
  tags:
    - ntp
