---
- name: gather os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/defaults.yml"

- name: install ntp Debian
  apt: name={{ v_ntp_package }} state=present
  when: ansible_os_family == "Debian"
  tags:
    - ntp
    - install

- name: install ntp RedHat
  yum: name={{ v_ntp_package }} state=present
  when: ansible_os_family == "RedHat"
  tags:
    - ntp
    - install

- name: ntp configuration file update
  template: src=ntp.conf.j2
    dest={{ v_ntp_config }}
    backup=yes
    owner=0 group=0 mode=0644
  notify:
    - restart ntp
  tags:
    - ntp
