---
- name: ensure correct locales exist
  locale_gen: name="{{ item }}" state=present
  with_items:
    - "{{ v_locales }}"
  notify:
    - update timezone

- name: set timezone
  file: src=/usr/share/zoneinfo/"{{ v_time_zone }}" dest=/etc/localtime state=link force=yes
  notify:
    - update timezone
