---
- name: install ntp
  apt: name=ntp state=present
  when: ansible_os_family == "Debian"

- name: install ntp
  yum: name=ntp state=present
  when: ansible_os_family == "RedHat"

- name: ntp configuration file update
  template: src=../files/ntp.conf.j2
    dest=/etc/ntp.conf
    backup=yes
    owner=0 group=0 mode=0644
  notify:
    - restart ntp
