---
- name: gather os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/defaults.yml"

- name: sshd configuration file update
  template: src=sshd_config.j2
    dest={{ v_ssh_config }}
    backup=yes
    owner=0 group=0 mode=0644
    validate='/usr/sbin/sshd -T -f %s'
  notify:
    - restart ssh
  tags:
    - ssh
