---
- name: create groups
  group: name={{ item }} state=present
  with_items:
    - "{{ v_groups }}"
  tags:
    - groups

- name: create users
  user: name={{ item.id }} shell=/bin/bash groups={{ item.groups }}
  with_items:
    - "{{ v_private_users }}"
  tags:
    - users

- name: add pub keys for users
  authorized_key: user={{ item.id }} key="{{ lookup('file', item.key) }}"
  with_items:
    - "{{ v_private_users }}"
  when: item.key is defined
  tags:
    - users
    - keys
