---
- name: restart server
  command: shutdown -r now "Restart triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true

- name: wait for server to restart
  local_action:
    module: wait_for
      host={{ ansible_ssh_host }}
      port={{ ansible_ssh_port }}
      delay=1
      timeout=300
    sudo: false
