---
# append all existing files with _delete
- name: delete old files
  shell: find /etc/sudoers.d/ -type f ! -name "custom" -exec mv {} {}_delete \;
  tags:
    - sudo

# add custom additions to sudoers
- name: add custom changes to sudoers.d
  template:
    src: custom.j2
    dest: /etc/sudoers.d/custom
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s
  tags:
    - sudo

# delete all files with _delete suffix
- name: delete old files
  shell: find /etc/sudoers.d/ -name "*_delete" -type f -exec rm -vf {} \;
  tags:
    - sudo
