---
- hosts: all
  sudo: yes
  gather_facts: yes
  vars_files:
    - "./private/vars/{{ ansible_os_family }}.yml"

  pre_tasks:

  roles:
    - ssh
    #- yum-update
    - yum
    - ntp
    - common

  tasks:

  post_tasks:
